//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topodata2.resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topodata2.resources.Strings.DatabaseParameters", typeof(DatabaseParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteFlipboard.
        /// </summary>
        internal static string DeleteFlipboard {
            get {
                return ResourceManager.GetString("DeleteFlipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteOurTeam.
        /// </summary>
        internal static string DeleteOurTeam {
            get {
                return ResourceManager.GetString("DeleteOurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM viewFlipboard.
        /// </summary>
        internal static string GetAllFlipboard {
            get {
                return ResourceManager.GetString("GetAllFlipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM viewOurTeam.
        /// </summary>
        internal static string GetAllOurTeam {
            get {
                return ResourceManager.GetString("GetAllOurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP(1) * FROM viewHomeSlideVideo ORDER BY RegHSData DESC.
        /// </summary>
        internal static string GetCurrentHomeSliderVideo {
            get {
                return ResourceManager.GetString("GetCurrentHomeSliderVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (1) * FROM viewFlipboard.
        /// </summary>
        internal static string GetFlipboardExists {
            get {
                return ResourceManager.GetString("GetFlipboardExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM viewOurTeam WHERE (Id = @value0).
        /// </summary>
        internal static string GetImagePathOurTeam {
            get {
                return ResourceManager.GetString("GetImagePathOurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (1) * FROM viewHomeSlideData ORDER BY regDate DESC.
        /// </summary>
        internal static string GetLastHomeSliderData {
            get {
                return ResourceManager.GetString("GetLastHomeSliderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP(1) * FROM viewTextoHome ORDER BY RegDate DESC.
        /// </summary>
        internal static string GetLastHomeText {
            get {
                return ResourceManager.GetString("GetLastHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertFlipboard.
        /// </summary>
        internal static string InsertFlipboard {
            get {
                return ResourceManager.GetString("InsertFlipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertHomeImageSeason.
        /// </summary>
        internal static string InsertHomeImageSeason {
            get {
                return ResourceManager.GetString("InsertHomeImageSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertHomeSlideVideo.
        /// </summary>
        internal static string InsertHomeSlideVideo {
            get {
                return ResourceManager.GetString("InsertHomeSlideVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertOurTeam.
        /// </summary>
        internal static string InsertOurTeam {
            get {
                return ResourceManager.GetString("InsertOurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertTextoHome.
        /// </summary>
        internal static string InsertTextoHome {
            get {
                return ResourceManager.GetString("InsertTextoHome", resourceCulture);
            }
        }
    }
}
