//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topodata2.resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Displays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Displays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topodata2.resources.Strings.Displays", typeof(Displays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrimensura.
        /// </summary>
        public static string Agrimensura {
            get {
                return ResourceManager.GetString("Agrimensura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area en Metros Cuadrados.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo que ocupa.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electronico.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseño.
        /// </summary>
        public static string Diseno {
            get {
                return ResourceManager.GetString("Diseno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio del Suelo.
        /// </summary>
        public static string EstudioSuelo {
            get {
                return ResourceManager.GetString("EstudioSuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link del video.
        /// </summary>
        public static string HomeSliderVideoUrlVideo {
            get {
                return ResourceManager.GetString("HomeSliderVideoUrlVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingenieria.
        /// </summary>
        public static string Ingenieria {
            get {
                return ResourceManager.GetString("Ingenieria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movil.
        /// </summary>
        public static string Movil {
            get {
                return ResourceManager.GetString("Movil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar una foto.
        /// </summary>
        public static string MustPhoto {
            get {
                return ResourceManager.GetString("MustPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. de Distrito Catastral.
        /// </summary>
        public static string NoDistrito {
            get {
                return ResourceManager.GetString("NoDistrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Matrícula del Título.
        /// </summary>
        public static string NoMatrical {
            get {
                return ResourceManager.GetString("NoMatrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Nombres {
            get {
                return ResourceManager.GetString("Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. de Parcela (Del Terreno).
        /// </summary>
        public static string NoParcela {
            get {
                return ResourceManager.GetString("NoParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion/Ubicacion exacta del terreno (Indique referencias).
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url de la revista.
        /// </summary>
        public static string UrlRevista {
            get {
                return ResourceManager.GetString("UrlRevista", resourceCulture);
            }
        }
    }
}
