//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topodata2.resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topodata2.resources.Strings.DomainSettings", typeof(DomainSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        public static string EmailAlternativeViewMediaType {
            get {
                return ResourceManager.GetString("EmailAlternativeViewMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacto@topodata.com.
        /// </summary>
        public static string EmailContact {
            get {
                return ResourceManager.GetString("EmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deslinde@topodata.com.
        /// </summary>
        public static string EmailDeslinde {
            get {
                return ResourceManager.GetString("EmailDeslinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@topodata.com.
        /// </summary>
        public static string EmailInfo {
            get {
                return ResourceManager.GetString("EmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topo.1953.
        /// </summary>
        public static string EmailInfoPassword {
            get {
                return ResourceManager.GetString("EmailInfoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_reply@topodata.com.
        /// </summary>
        public static string EmailNo_reply {
            get {
                return ResourceManager.GetString("EmailNo_reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrados@topodata.com.
        /// </summary>
        public static string EmailRegistrados {
            get {
                return ResourceManager.GetString("EmailRegistrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo de un visitante.
        /// </summary>
        public static string EmailSubjectSendContactUs {
            get {
                return ResourceManager.GetString("EmailSubjectSendContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Deslinde Registrado.
        /// </summary>
        public static string EmailSubjectSendDeslindeRegistrationAdmin {
            get {
                return ResourceManager.GetString("EmailSubjectSendDeslindeRegistrationAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso de gestion de Título iniciado.
        /// </summary>
        public static string EmailSubjectSendDeslindeRegistrationUser {
            get {
                return ResourceManager.GetString("EmailSubjectSendDeslindeRegistrationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última NOTICIA de TOPODATA del sector Construcción.
        /// </summary>
        public static string EmailSubjectSendHomeVideoUpload {
            get {
                return ResourceManager.GetString("EmailSubjectSendHomeVideoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVO!! Documento Técnico.
        /// </summary>
        public static string EmailSubjectSendNewDocumentMessage {
            get {
                return ResourceManager.GetString("EmailSubjectSendNewDocumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducete a TOPODATA.
        /// </summary>
        public static string EmailSubjectSendRegistrationDone {
            get {
                return ResourceManager.GetString("EmailSubjectSendRegistrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Topodata Registrado.
        /// </summary>
        public static string EmailSubjectSendRegistrationDoneAdmin {
            get {
                return ResourceManager.GetString("EmailSubjectSendRegistrationDoneAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por Suscribirte a TOPODATA!.
        /// </summary>
        public static string EmailSubjectSendSubscribeDone {
            get {
                return ResourceManager.GetString("EmailSubjectSendSubscribeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testt@topodata.com.
        /// </summary>
        public static string EmailTestt {
            get {
                return ResourceManager.GetString("EmailTestt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.topodata.com.
        /// </summary>
        public static string HostEmail {
            get {
                return ResourceManager.GetString("HostEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.topodata.com.
        /// </summary>
        public static string HostHome {
            get {
                return ResourceManager.GetString("HostHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string HostPortSend {
            get {
                return ResourceManager.GetString("HostPortSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTH LOGIN.
        /// </summary>
        public static string HostSparkpostAuthentication {
            get {
                return ResourceManager.GetString("HostSparkpostAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTTLS.
        /// </summary>
        public static string HostSparkpostEncryption {
            get {
                return ResourceManager.GetString("HostSparkpostEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59b70763f9429e4e54295dd07ad651727f6618f1.
        /// </summary>
        public static string HostSparkpostKey {
            get {
                return ResourceManager.GetString("HostSparkpostKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.sparkpostmail.com.
        /// </summary>
        public static string HostSparkpostMail {
            get {
                return ResourceManager.GetString("HostSparkpostMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string HostSparkpostPortSend {
            get {
                return ResourceManager.GetString("HostSparkpostPortSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP_Injection.
        /// </summary>
        public static string HostSparkpostUsername {
            get {
                return ResourceManager.GetString("HostSparkpostUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topodata.com/Services/Document/.
        /// </summary>
        public static string UrlDocument {
            get {
                return ResourceManager.GetString("UrlDocument", resourceCulture);
            }
        }
    }
}
