//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topodata2.resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topodata2.resources.Strings.MailParameters", typeof(MailParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBAQFBAYFBQYJBgUGCQsIBgYICwwKCgsKCgwQDAwMDAwMEAwODxAPDgwTExQUExMcGxsbHB8fHx8fHx8fHx//2wBDAQcHBw0MDRgQEBgaFREVGh8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx//wAARCADKAfQDAREAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAABQIDBAYHAQAI/8QASxAAAgEDAgQDBQYBCQUGBgMAAQIDAAQRBSEGEjFBEyJRBzJhcYEUIzNCkaEIFTVDUmJyscHRFiQ0c8I2U4KisuEXJUSS8PE3Y7P/xAAaAQACAwEBAAAAAAAAAAAAAAAAAgEDBAUG/8QAKhEAAgICAwABBQACAgMBAAAAAAECEQMhBBIxQQUTIjJRFGEzcRVCgSP/2gAMAwEAAhEDEQA/APo6gkUtQwOyHAoAjtQS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeslindePeople {
            get {
                return ResourceManager.GetString("DeslindePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people500x202.jpg.
        /// </summary>
        internal static string DeslindePeopleName {
            get {
                return ResourceManager.GetString("DeslindePeopleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topodata.
        /// </summary>
        internal static string DisplayNameInfo {
            get {
                return ResourceManager.GetString("DisplayNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyNpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconFacebookHomeVideo {
            get {
                return ResourceManager.GetString("IconFacebookHomeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_facebook.png.
        /// </summary>
        internal static string IconFacebookHomeVideoName {
            get {
                return ResourceManager.GetString("IconFacebookHomeVideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyNpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconTwitterHomeVideo {
            get {
                return ResourceManager.GetString("IconTwitterHomeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_twitter.png.
        /// </summary>
        internal static string IconTwitterHomeVideoName {
            get {
                return ResourceManager.GetString("IconTwitterHomeVideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyNpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconYoutubeHomeVideo {
            get {
                return ResourceManager.GetString("IconYoutubeHomeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_youtube.png.
        /// </summary>
        internal static string IconYoutubeHomeVideoName {
            get {
                return ResourceManager.GetString("IconYoutubeHomeVideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/png.
        /// </summary>
        internal static string ImageTyePng {
            get {
                return ResourceManager.GetString("ImageTyePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/gif.
        /// </summary>
        internal static string ImageTypeGif {
            get {
                return ResourceManager.GetString("ImageTypeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        internal static string ImageTypeJpeg {
            get {
                return ResourceManager.GetString("ImageTypeJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R0lGODlhZABgAMQAAPfy+J2YnQCqAExJS1/jHX3xKY3jiyMgIF7SXzvREqv/O9TT1Nb/pbr+eIT+DsfyyOn+2cD/Qenk68W9xjzEPQChAIaDhuDK5LKtsxu/Da/zr21qbJb/MgC0AAAAAP///yH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS41LWMwMjEgNzkuMTU1NzcyLCAyMDE0LzAxLzEzLTE5OjQ0OjAwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logo100x95 {
            get {
                return ResourceManager.GetString("Logo100x95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logoDefault100x95.gif.
        /// </summary>
        internal static string Logo100x95Name {
            get {
                return ResourceManager.GetString("Logo100x95Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R0lGODlhTABJAMQAAJ+Tn/bz9gCnAFbfGl1XXCzIGHzwKZTkldDP0K3/O1rWWhoWGM79zNL/mYb+ELj/b/H/0sb/Q7u5u+Tf5oiCibKls7T2tOH45UlDSd++43NvdDQuM5b/MgC0AAAAAP///yH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS41LWMwMjEgNzkuMTU1NzcyLCAyMDE0LzAxLzEzLTE5OjQ0OjAwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logo76x72 {
            get {
                return ResourceManager.GetString("Logo76x72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logoDefault76x72.gif.
        /// </summary>
        internal static string Logo76x72Name {
            get {
                return ResourceManager.GetString("Logo76x72Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imagenDelDocumento.
        /// </summary>
        internal static string NewDocumentName {
            get {
                return ResourceManager.GetString("NewDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALCwsMCxAMDBAXDw0PFxsUEBAUGx8XFxcXFx8eFxoaGhoXHh4jJSclIx4vLzMzLy9AQEBAQEBAQEBAQEBAQED/2wBDAREPDxETERUSEhUUERQRFBoUFhYUGiYaGhwaGiYwIx4eHh4jMCsuJycnLis1NTAwNTVAQD9AQEBAQEBAQEBAQED/wAARCAFNAfQDASIAAhEBAxEB/8QAGwAAAQUBAQAAAAAAAAAAAAAAAgABAwQFBgf/xABJEAABAwIEAgcEBggDBwQDAAABAAIDBBEFEiExQVEGEyIyYXGBFEKRoSNSYrHB0QcVFjNDcpLSgqLhJCVTVGOywiY1g/BEc+L/xAAaAQADAQEBAQAAAAAAAAAAAAAAAQIDBAUG/8QANREAAgIBAwIEBAMIAgMAAAAAAAECEQMSITFBUQQiYZETQnGBMlKhBRRicrHB0fAjM0PC4f/aAAwDAQACEQMRAD8AltdDKdmj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrationDoneUser {
            get {
                return ResourceManager.GetString("RegistrationDoneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to architect.jpg.
        /// </summary>
        internal static string RegistrationDoneUserName {
            get {
                return ResourceManager.GetString("RegistrationDoneUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo de un visitante.
        /// </summary>
        internal static string SubjectContactUs {
            get {
                return ResourceManager.GetString("SubjectContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Deslinde Registrado.
        /// </summary>
        internal static string SubjectDeslindeRegistrationAdmin {
            get {
                return ResourceManager.GetString("SubjectDeslindeRegistrationAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso de gestion de Título iniciado.
        /// </summary>
        internal static string SubjectDeslindeRegistrationUser {
            get {
                return ResourceManager.GetString("SubjectDeslindeRegistrationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última NOTICIA de TOPODATA del sector Construcción.
        /// </summary>
        internal static string SubjectHomeVideoUpload {
            get {
                return ResourceManager.GetString("SubjectHomeVideoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVO!! Documento Técnico.
        /// </summary>
        internal static string SubjectNewDocumentMessage {
            get {
                return ResourceManager.GetString("SubjectNewDocumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducete a TOPODATA.
        /// </summary>
        internal static string SubjectRegistrationDone {
            get {
                return ResourceManager.GetString("SubjectRegistrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Topodata Registrado.
        /// </summary>
        internal static string SubjectRegistrationDoneAdmin {
            get {
                return ResourceManager.GetString("SubjectRegistrationDoneAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por Suscribirte a TOPODATA!.
        /// </summary>
        internal static string SubjectSubscribeDone {
            get {
                return ResourceManager.GetString("SubjectSubscribeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBAQFBAYFBQYJBgUGCQsIBgYICwwKCgsKCgwQDAwMDAwMEAwODxAPDgwTExQUExMcGxsbHB8fHx8fHx8fHx//2wBDAQcHBw0MDRgQEBgaFREVGh8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx//wAARCAFNAfQDAREAAhEBAxEB/8QAHQAAAQUBAQEBAAAAAAAAAAAAAAMEBQYHCAIBCf/EAFMQAAIBAwMBBQUFBQUFBAcGBwECAwAEEQUSIQYHEzFBURQiMmFxI0KBkbEIFVKhwRYzYnKSJENTgtEXNKKyGCVEc4Ph8SY1VGTC4mWTo7PD0vD/xAAbAQABBQEBAAAAAAAAAAAAAAAAAQIDBAUGB//EAEERAAIBAwICBggFAQYGAwEAAAABAgMEERIhBTETIjJBUfAGYXGBobHB0RQjQlKRM1OCosLh8RUWJGJy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubscribeDone {
            get {
                return ResourceManager.GetString("SubscribeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribeDone500x333.jpg.
        /// </summary>
        internal static string SubscribeDoneName {
            get {
                return ResourceManager.GetString("SubscribeDoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added-home-video.
        /// </summary>
        internal static string TemplateIdAddedHomeVideo {
            get {
                return ResourceManager.GetString("TemplateIdAddedHomeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new-document-added.
        /// </summary>
        internal static string TemplateIdNewDocumentAdded {
            get {
                return ResourceManager.GetString("TemplateIdNewDocumentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration-done-user.
        /// </summary>
        internal static string TemplateIdRegistrationDoneUser {
            get {
                return ResourceManager.GetString("TemplateIdRegistrationDoneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribe-done-user.
        /// </summary>
        internal static string TemplateIdSubscribeDoneUser {
            get {
                return ResourceManager.GetString("TemplateIdSubscribeDoneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i.imgur.com/JDJFsq0.jpg.
        /// </summary>
        internal static string VolanteTopogisWeb {
            get {
                return ResourceManager.GetString("VolanteTopogisWeb", resourceCulture);
            }
        }
    }
}
