//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topodata2.resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topodata2.resources.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo invalido.
        /// </summary>
        public static string CorreoInvalido {
            get {
                return ResourceManager.GetString("CorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede estar en blanco.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha sucedido un error desconocido, favor intentar mas tarde.
        /// </summary>
        public static string ErrorDesconocido {
            get {
                return ResourceManager.GetString("ErrorDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha sucedido un error realizando la operacion..
        /// </summary>
        public static string ErrorRealizandoOperacion {
            get {
                return ResourceManager.GetString("ErrorRealizandoOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe tener un maximo de 200 caracteres.
        /// </summary>
        public static string Max200Char {
            get {
                return ResourceManager.GetString("Max200Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe tener maximo 50 caracteres.
        /// </summary>
        public static string Max50Char {
            get {
                return ResourceManager.GetString("Max50Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ser un link de una revista de topodata en Flipboard.
        /// </summary>
        public static string MustTopodataFlipboard {
            get {
                return ResourceManager.GetString("MustTopodataFlipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor escriba algun mensaje.
        /// </summary>
        public static string MustWrite {
            get {
                return ResourceManager.GetString("MustWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es requerido.
        /// </summary>
        public static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene que seleccionar una imagen de formato GIF, JPG o PNG.
        /// </summary>
        public static string TieneFormatoImagen {
            get {
                return ResourceManager.GetString("TieneFormatoImagen", resourceCulture);
            }
        }
    }
}
