//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topodata2.resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topodata2.resources.Strings.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/ContactUsAdmin.html.
        /// </summary>
        public static string EmailTemplateContactUsAdmin {
            get {
                return ResourceManager.GetString("EmailTemplateContactUsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/Deslinder/DeslinderUserRegisteredAdmin.html.
        /// </summary>
        public static string EmailTemplateDeslindeUserRegisteredAdmin {
            get {
                return ResourceManager.GetString("EmailTemplateDeslindeUserRegisteredAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/Deslinder/DeslinderUserRegisteredUser.html.
        /// </summary>
        public static string EmailTemplateDeslindeUserRegisteredUser {
            get {
                return ResourceManager.GetString("EmailTemplateDeslindeUserRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/HomeVideo.html.
        /// </summary>
        public static string EmailTemplateHomeVideoAdded {
            get {
                return ResourceManager.GetString("EmailTemplateHomeVideoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/AddedContent/NewDocumentAdded.html.
        /// </summary>
        public static string EmailTemplateNewDocumentAdded {
            get {
                return ResourceManager.GetString("EmailTemplateNewDocumentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/Registration/RegistrationDoneUser.html.
        /// </summary>
        public static string EmailTemplateRegistrationDoneUser {
            get {
                return ResourceManager.GetString("EmailTemplateRegistrationDoneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/Registration/RegistrationDoneUserAdmin.html.
        /// </summary>
        public static string EmailTemplateRegistrationDoneUserAdmin {
            get {
                return ResourceManager.GetString("EmailTemplateRegistrationDoneUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/Subscribe/SubscribedDone/SubscribedDoneMin.html.
        /// </summary>
        public static string EmailTemplateSubscribedDoneMin {
            get {
                return ResourceManager.GetString("EmailTemplateSubscribedDoneMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/Deslinder/images/people.jpg.
        /// </summary>
        public static string ImgDeslindePeople {
            get {
                return ResourceManager.GetString("ImgDeslindePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/resources/img/email/architect.jpg.
        /// </summary>
        public static string ImgEmailArchitect {
            get {
                return ResourceManager.GetString("ImgEmailArchitect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/resources/img/email/subscribeDone.jpg.
        /// </summary>
        public static string ImgEmailSubscribeDone {
            get {
                return ResourceManager.GetString("ImgEmailSubscribeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/img/icons/icon_facebook.png.
        /// </summary>
        public static string imgHomeVideoIconFacebook {
            get {
                return ResourceManager.GetString("imgHomeVideoIconFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/img/icons/icon_twitter.png.
        /// </summary>
        public static string imgHomeVideoIconTwitter {
            get {
                return ResourceManager.GetString("imgHomeVideoIconTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/EmailTemplates/img/icons/icon_youtube.png.
        /// </summary>
        public static string imgHomeVideoIconYoutube {
            get {
                return ResourceManager.GetString("imgHomeVideoIconYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/resources/img/logoDefault.png.
        /// </summary>
        public static string ImgLogoDefault {
            get {
                return ResourceManager.GetString("ImgLogoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/resources/img/icons/volantetopogis.jpg.
        /// </summary>
        public static string ImgVolanteTopogis {
            get {
                return ResourceManager.GetString("ImgVolanteTopogis", resourceCulture);
            }
        }
    }
}
